version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "UTC"
    labels:
      - "kind/task"
      - "status/todo"
    open-pull-requests-limit: 3
    rebase-strategy: "auto"
    commit-message:
      prefix: "chore(deps)"
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "UTC"
    labels:
      - "kind/task"
      - "status/todo"
    open-pull-requests-limit: 3
    rebase-strategy: "auto"
    commit-message:
      prefix: "chore(vendor)"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "UTC"
    labels:
      - "kind/task"
      - "status/todo"
    open-pull-requests-limit: 3
    rebase-strategy: "auto"
    commit-message:
      prefix: "ci(actions)"
    groups:
      github-actions:
        patterns:
          - "*"
